/*
 *  include FILE <gg/public.inc>
 *
 *  Free Software Klausel fuer Utilities
 *
 *  written:       1986-01-01
 *  latest update: 1999-12-20 21:25:41
 *  $Id: public.inc,v 1.2 2011/12/25 08:53:48 gonter Exp $
 *
 */

"(c) 1986..2012 Gerhard Gonter;            comments to <g.gonter@ieee.org> !!\n",
"This is free software like FreeBSD or Perl.\n",
"You may distribute this program freely under the terms of the FreeBSD license.\n",
"See http://www.freebsd.org/copyright/freebsd-license.html\n",
#ifdef MSDOS
,
"(RETURN)\n"
#endif
